---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: file
  name: image
  label: image
- type: text
  name: video
  label: video
  description: 'Ex: https://www.youtube-nocookie.com/embed/3NeCmZOwP4w'
- type: list
  name: credits
  label: credits
  description: "['Alfie the Annoying', 'Sam']"
- type: text
  name: description
  label: description
  description: this is meta description
- type: list
  name: tags
  label: tags
pages:
- project/test-project.md
